// src/slowka.js
// Slownictwo minigry "Tlumaczenia" - angielskie slowo -> lista akceptowanych
// polskich odpowiedzi. Wzorem src/countries.js (tam: kraj -> warianty nazwy).
//
// Kazdy wpis w RAW to [angielskieSlowo, podstawowePolskieTlumaczenie, opcjonalnaListaDodatkowychWariantow].
// Zbudowany na tej podstawie SLOWKA[en] daje PODSTAWOWE tlumaczenie (do
// wyswietlenia w ewentualnym podsumowaniu), a getAkceptowaneWarianty(en)
// zwraca WSZYSTKIE zaakceptowane odpowiedzi (podstawowa + warianty),
// znormalizowane przez normalizePolish (patrz src/vanessa.js - ta sama
// funkcja jest juz uzywana w calym projekcie, wiec porownanie jest odporne
// na polskie znaki i wielkosc liter bez pisania wlasnej kopii).
//
// Dobor slownictwa: rzeczy codzienne, ktore polski czat streamu realnie zna -
// bez slownictwa specjalistycznego i archaizmow. Celowo POMIJAMY slowa
// wieloznaczne bez kontekstu, ktorych sama flashcardowa forma ("jedno slowo
// angielskie -> ?") nie rozstrzyga (np. "bank" - instytucja finansowa czy
// brzeg rzeki, "light" - swiatlo czy lekki, "right" - prawo/prawy/racja,
// "spring" - wiosna/sprezyna/skakac, "watch" - zegarek czy patrzec,
// "second" - sekunda czy drugi) - dla tych, ktore mimo wszystko zostaly (np.
// "market", "short", "hard", "free", "top", "line", "corner", "volume",
// "party", "iron", "pepper", "goal", "glass", "chips", "letter", "race",
// "cool", "dream"), podajemy w
// wariantach KOMPLET sensownych tlumaczen zamiast jednego, zeby nie odrzucac
// poprawnych odpowiedzi.
//
// Brak duplikatow po stronie angielskiej: sprawdzane w RUNTIME nizej (rzuca
// wyjatkiem przy ladowaniu modulu, gdyby ktos przez pomylke dodal ten sam
// klucz dwa razy) - to jest silniejsza gwarancja niz recznie przeliczanie.
import { normalizePolish } from './vanessa.js';

const RAW = [
  // --- Liczby ---
  ['zero', 'zero'],
  ['one', 'jeden'],
  ['two', 'dwa'],
  ['three', 'trzy'],
  ['four', 'cztery'],
  ['five', 'piec'],
  ['six', 'szesc'],
  ['seven', 'siedem'],
  ['eight', 'osiem'],
  ['nine', 'dziewiec'],
  ['ten', 'dziesiec'],
  ['eleven', 'jedenascie'],
  ['twelve', 'dwanascie'],
  ['thirteen', 'trzynascie'],
  ['fourteen', 'czternascie'],
  ['fifteen', 'pietnascie'],
  ['sixteen', 'szesnascie'],
  ['seventeen', 'siedemnascie'],
  ['eighteen', 'osiemnascie'],
  ['nineteen', 'dziewietnascie'],
  ['twenty', 'dwadziescia'],
  ['thirty', 'trzydziesci'],
  ['forty', 'czterdziesci'],
  ['fifty', 'piecdziesiat'],
  ['sixty', 'szescdziesiat'],
  ['seventy', 'siedemdziesiat'],
  ['eighty', 'osiemdziesiat'],
  ['ninety', 'dziewiecdziesiat'],
  ['hundred', 'sto'],
  ['thousand', 'tysiac'],
  ['first', 'pierwszy'],
  ['third', 'trzeci'],
  ['fourth', 'czwarty'],
  ['fifth', 'piaty'],
  ['last', 'ostatni'],

  // --- Kolory ---
  ['red', 'czerwony'],
  ['blue', 'niebieski'],
  ['green', 'zielony'],
  ['yellow', 'zolty'],
  ['black', 'czarny'],
  ['white', 'bialy'],
  ['orange', 'pomaranczowy'],
  ['purple', 'fioletowy'],
  ['pink', 'rozowy'],
  ['brown', 'brazowy'],
  ['gray', 'szary', ['grey']],
  ['gold', 'zloty'],
  ['silver', 'srebrny'],

  // --- Rodzina ---
  ['mother', 'matka', ['mama']],
  ['father', 'ojciec', ['tata']],
  ['sister', 'siostra'],
  ['brother', 'brat'],
  ['son', 'syn'],
  ['daughter', 'corka'],
  ['grandmother', 'babcia'],
  ['grandfather', 'dziadek'],
  ['aunt', 'ciocia', ['ciotka']],
  ['uncle', 'wujek', ['wuj']],
  ['cousin', 'kuzyn', ['kuzynka']],
  ['wife', 'zona'],
  ['husband', 'maz'],
  ['baby', 'dziecko', ['niemowle']],
  ['child', 'dziecko'],
  ['parents', 'rodzice'],
  ['family', 'rodzina'],
  ['friend', 'przyjaciel', ['kolega', 'kolezanka', 'znajomy']],

  // --- Zwierzeta ---
  ['dog', 'pies'],
  ['cat', 'kot'],
  ['horse', 'kon'],
  ['cow', 'krowa'],
  ['pig', 'swinia'],
  ['sheep', 'owca'],
  ['chicken', 'kurczak', ['kura']],
  ['duck', 'kaczka'],
  ['goose', 'ges'],
  ['rabbit', 'krolik'],
  ['mouse', 'mysz'],
  ['bird', 'ptak'],
  ['fish', 'ryba'],
  ['lion', 'lew'],
  ['tiger', 'tygrys'],
  ['bear', 'niedzwiedz'],
  ['elephant', 'slon'],
  ['monkey', 'malpa'],
  ['wolf', 'wilk'],
  ['fox', 'lis'],
  ['deer', 'jelen'],
  ['snake', 'waz'],
  ['frog', 'zaba'],
  ['turtle', 'zolw'],
  ['spider', 'pajak'],
  ['bee', 'pszczola'],
  ['butterfly', 'motyl'],
  ['ant', 'mrowka'],
  ['owl', 'sowa'],
  ['shark', 'rekin'],
  ['whale', 'wieloryb'],
  ['dolphin', 'delfin'],
  ['squirrel', 'wiewiorka'],
  ['hedgehog', 'jez'],
  ['camel', 'wielblad'],
  ['giraffe', 'zyrafa'],
  ['zebra', 'zebra'],
  ['kangaroo', 'kangur'],
  ['penguin', 'pingwin'],
  ['goat', 'koza'],
  ['donkey', 'osiol'],
  ['crab', 'krab'],
  ['lobster', 'homar'],
  ['snail', 'slimak'],
  ['worm', 'robak'],
  ['mosquito', 'komar'],
  ['ladybug', 'biedronka'],
  ['parrot', 'papuga'],
  ['hamster', 'chomik'],
  ['lizard', 'jaszczurka'],
  ['crocodile', 'krokodyl'],
  ['seal', 'foka'],
  ['octopus', 'osmiornica'],
  ['eagle', 'orzel'],
  ['sparrow', 'wrobel'],
  ['pigeon', 'golab'],
  ['swan', 'labedz'],
  ['peacock', 'paw'],
  ['rooster', 'kogut'],

  // --- Jedzenie i picie ---
  ['bread', 'chleb'],
  ['butter', 'maslo'],
  ['cheese', 'ser'],
  ['milk', 'mleko'],
  ['egg', 'jajko'],
  ['meat', 'mieso'],
  ['rice', 'ryz'],
  ['pasta', 'makaron'],
  ['soup', 'zupa'],
  ['salad', 'salatka'],
  ['sugar', 'cukier'],
  ['salt', 'sol'],
  ['pepper', 'pieprz', ['papryka']],
  ['water', 'woda'],
  ['juice', 'sok'],
  ['coffee', 'kawa'],
  ['tea', 'herbata'],
  ['beer', 'piwo'],
  ['wine', 'wino'],
  ['apple', 'jablko'],
  ['banana', 'banan'],
  ['grape', 'winogrono'],
  ['strawberry', 'truskawka'],
  ['lemon', 'cytryna'],
  ['watermelon', 'arbuz'],
  ['pineapple', 'ananas'],
  ['cherry', 'wisnia', ['czeresnia']],
  ['peach', 'brzoskwinia'],
  ['pear', 'gruszka'],
  ['potato', 'ziemniak'],
  ['tomato', 'pomidor'],
  ['onion', 'cebula'],
  ['carrot', 'marchewka'],
  ['cucumber', 'ogorek'],
  ['cabbage', 'kapusta'],
  ['mushroom', 'grzyb'],
  ['corn', 'kukurydza'],
  ['garlic', 'czosnek'],
  ['honey', 'miod'],
  ['chocolate', 'czekolada'],
  ['candy', 'cukierek'],
  ['cake', 'ciasto', ['tort']],
  ['cookie', 'ciastko'],
  ['ice cream', 'lody'],
  ['sandwich', 'kanapka'],
  ['pizza', 'pizza'],
  ['breakfast', 'sniadanie'],
  ['lunch', 'obiad'],
  ['dinner', 'kolacja', ['obiad']],
  ['meal', 'posilek'],
  ['restaurant', 'restauracja'],
  ['plate', 'talerz'],
  ['cup', 'kubek', ['filizanka']],
  ['glass', 'szklanka', ['szklo']],
  ['spoon', 'lyzka'],
  ['fork', 'widelec'],
  ['knife', 'noz'],
  ['bottle', 'butelka'],
  ['bowl', 'miska'],
  ['yogurt', 'jogurt'],
  ['jam', 'dzem'],
  ['flour', 'maka'],
  ['oil', 'olej'],
  ['vinegar', 'ocet'],
  ['noodles', 'makaron'],
  ['sausage', 'kielbasa'],
  ['ham', 'szynka'],
  ['bacon', 'boczek'],
  ['steak', 'stek'],
  ['burger', 'burger', ['hamburger']],
  ['chips', 'chipsy', ['frytki']],
  ['french fries', 'frytki'],
  ['popcorn', 'popcorn'],
  ['nuts', 'orzechy'],
  ['almond', 'migdal'],
  ['peanut', 'orzeszek ziemny'],
  ['lettuce', 'salata'],
  ['spinach', 'szpinak'],
  ['broccoli', 'brokul'],
  ['pea', 'groszek'],
  ['bean', 'fasola'],
  ['pumpkin', 'dynia'],
  ['melon', 'melon'],
  ['mango', 'mango'],
  ['kiwi', 'kiwi'],
  ['coconut', 'kokos'],
  ['raisin', 'rodzynek'],
  ['sauce', 'sos'],
  ['spice', 'przyprawa'],
  ['herb', 'zioło', ['ziolo']],
  ['recipe', 'przepis'],
  ['ingredient', 'skladnik'],

  // --- Dom ---
  ['house', 'dom'],
  ['home', 'dom'],
  ['room', 'pokoj'],
  ['kitchen', 'kuchnia'],
  ['bathroom', 'lazienka'],
  ['bedroom', 'sypialnia'],
  ['garden', 'ogrod'],
  ['door', 'drzwi'],
  ['window', 'okno'],
  ['wall', 'sciana'],
  ['floor', 'podloga'],
  ['roof', 'dach'],
  ['table', 'stol'],
  ['chair', 'krzeslo'],
  ['sofa', 'kanapa'],
  ['bed', 'lozko'],
  ['lamp', 'lampa'],
  ['mirror', 'lustro'],
  ['key', 'klucz'],
  ['clock', 'zegar'],
  ['picture', 'obraz', ['zdjecie']],
  ['shelf', 'polka'],
  ['carpet', 'dywan'],
  ['curtain', 'zaslona'],
  ['stairs', 'schody'],
  ['garage', 'garaz'],
  ['fence', 'plot'],
  ['ceiling', 'sufit'],
  ['soap', 'mydlo'],
  ['towel', 'recznik'],
  ['toothbrush', 'szczoteczka do zebow'],
  ['toilet', 'toaleta'],
  ['sink', 'zlew', ['umywalka']],
  ['shower', 'prysznic'],
  ['bathtub', 'wanna'],
  ['blanket', 'koc'],
  ['pillow', 'poduszka'],
  ['sheet', 'przescieradlo'],
  ['wardrobe', 'szafa', ['closet']],
  ['drawer', 'szuflada'],
  ['box', 'pudelko', ['skrzynka']],
  ['basket', 'kosz'],
  ['broom', 'miotla'],
  ['bucket', 'wiadro'],
  ['candle', 'swieca'],
  ['lock', 'zamek'],
  ['bulb', 'zarowka'],
  ['switch', 'przelacznik', ['wylacznik']],
  ['plug', 'wtyczka'],
  ['socket', 'gniazdko'],
  ['iron', 'zelazko', ['zelazo']],
  ['fridge', 'lodowka', ['refrigerator']],
  ['oven', 'piekarnik'],
  ['stove', 'kuchenka'],
  ['microwave', 'mikrofalowka'],
  ['dishwasher', 'zmywarka'],
  ['washing machine', 'pralka'],
  ['kettle', 'czajnik'],
  ['toaster', 'toster'],

  // --- Ubrania ---
  ['shirt', 'koszula'],
  ['t-shirt', 'koszulka'],
  ['trousers', 'spodnie', ['pants']],
  ['dress', 'sukienka'],
  ['skirt', 'spodnica'],
  ['jacket', 'kurtka'],
  ['coat', 'plaszcz'],
  ['shoes', 'buty'],
  ['socks', 'skarpetki'],
  ['hat', 'czapka', ['kapelusz']],
  ['gloves', 'rekawiczki'],
  ['scarf', 'szalik'],
  ['belt', 'pasek'],
  ['sweater', 'sweter'],
  ['jeans', 'dzinsy'],
  ['shorts', 'szorty'],
  ['tie', 'krawat'],
  ['glasses', 'okulary'],
  ['umbrella', 'parasol'],
  ['bag', 'torba'],
  ['backpack', 'plecak'],
  ['wallet', 'portfel'],

  // --- Czesci ciala ---
  ['head', 'glowa'],
  ['hair', 'wlosy'],
  ['face', 'twarz'],
  ['eye', 'oko'],
  ['ear', 'ucho'],
  ['nose', 'nos'],
  ['mouth', 'usta'],
  ['tooth', 'zab'],
  ['tongue', 'jezyk'],
  ['neck', 'szyja'],
  ['shoulder', 'bark'],
  ['arm', 'ramie'],
  ['hand', 'reka'],
  ['finger', 'palec'],
  ['leg', 'noga'],
  ['foot', 'stopa'],
  ['knee', 'kolano'],
  ['elbow', 'lokiec'],
  ['stomach', 'brzuch'],
  ['heart', 'serce'],
  ['skin', 'skora'],
  ['blood', 'krew'],

  // --- Przyroda i pogoda ---
  ['sun', 'slonce'],
  ['moon', 'ksiezyc'],
  ['star', 'gwiazda'],
  ['sky', 'niebo'],
  ['cloud', 'chmura'],
  ['rain', 'deszcz'],
  ['snow', 'snieg'],
  ['wind', 'wiatr'],
  ['storm', 'burza'],
  ['fog', 'mgla'],
  ['ice', 'lod'],
  ['fire', 'ogien'],
  ['earth', 'ziemia'],
  ['mountain', 'gora'],
  ['river', 'rzeka'],
  ['lake', 'jezioro'],
  ['sea', 'morze'],
  ['ocean', 'ocean'],
  ['forest', 'las'],
  ['tree', 'drzewo'],
  ['flower', 'kwiat'],
  ['grass', 'trawa'],
  ['leaf', 'lisc'],
  ['stone', 'kamien'],
  ['sand', 'piasek'],
  ['island', 'wyspa'],
  ['beach', 'plaza'],
  ['desert', 'pustynia'],
  ['valley', 'dolina'],
  ['hill', 'wzgorze'],

  // --- Czas i kalendarz ---
  ['day', 'dzien'],
  ['night', 'noc'],
  ['morning', 'rano', ['poranek']],
  ['evening', 'wieczor'],
  ['afternoon', 'popoludnie'],
  ['week', 'tydzien'],
  ['month', 'miesiac'],
  ['year', 'rok'],
  ['today', 'dzisiaj'],
  ['tomorrow', 'jutro'],
  ['yesterday', 'wczoraj'],
  ['hour', 'godzina'],
  ['minute', 'minuta'],
  ['monday', 'poniedzialek'],
  ['tuesday', 'wtorek'],
  ['wednesday', 'sroda'],
  ['thursday', 'czwartek'],
  ['friday', 'piatek'],
  ['saturday', 'sobota'],
  ['sunday', 'niedziela'],
  ['january', 'styczen'],
  ['february', 'luty'],
  ['march', 'marzec'],
  ['april', 'kwiecien'],
  ['june', 'czerwiec'],
  ['july', 'lipiec'],
  ['august', 'sierpien'],
  ['september', 'wrzesien'],
  ['october', 'pazdziernik'],
  ['november', 'listopad'],
  ['december', 'grudzien'],
  ['season', 'pora roku'],
  ['summer', 'lato'],
  ['winter', 'zima'],
  ['autumn', 'jesien'],
  ['birthday', 'urodziny'],
  ['wedding', 'slub'],
  ['funeral', 'pogrzeb'],

  // --- Szkola ---
  ['school', 'szkola'],
  ['teacher', 'nauczyciel'],
  ['student', 'uczen', ['student']],
  ['book', 'ksiazka'],
  ['pen', 'dlugopis'],
  ['pencil', 'olowek'],
  ['notebook', 'zeszyt'],
  ['desk', 'biurko'],
  ['classroom', 'klasa'],
  ['lesson', 'lekcja'],
  ['homework', 'praca domowa', ['zadanie domowe']],
  ['exam', 'egzamin'],
  ['question', 'pytanie'],
  ['answer', 'odpowiedz'],
  ['word', 'slowo'],
  ['sentence', 'zdanie'],
  ['letter', 'litera', ['list']],
  ['number', 'liczba', ['numer']],
  ['page', 'strona'],
  ['library', 'biblioteka'],
  ['university', 'uniwersytet'],

  // --- Praca ---
  ['work', 'praca'],
  ['job', 'praca', ['zawod']],
  ['boss', 'szef'],
  ['manager', 'kierownik'],
  ['doctor', 'lekarz'],
  ['nurse', 'pielegniarka'],
  ['engineer', 'inzynier'],
  ['policeman', 'policjant'],
  ['firefighter', 'strazak'],
  ['farmer', 'rolnik'],
  ['cook', 'kucharz'],
  ['driver', 'kierowca'],
  ['pilot', 'pilot'],
  ['soldier', 'zolnierz'],
  ['lawyer', 'prawnik'],
  ['dentist', 'dentysta'],
  ['waiter', 'kelner'],
  ['cashier', 'kasjer'],
  ['builder', 'budowniczy', ['murarz']],
  ['artist', 'artysta'],
  ['singer', 'piosenkarz'],
  ['actor', 'aktor'],
  ['musician', 'muzyk'],
  ['writer', 'pisarz'],
  ['salary', 'pensja', ['wynagrodzenie']],
  ['money', 'pieniadze'],
  ['office', 'biuro'],
  ['factory', 'fabryka'],
  ['company', 'firma', ['spolka']],
  ['meeting', 'spotkanie'],
  ['customer', 'klient'],

  // --- Sport ---
  ['football', 'pilka nozna', ['soccer']],
  ['basketball', 'koszykowka'],
  ['volleyball', 'siatkowka'],
  ['tennis', 'tenis'],
  ['swimming', 'plywanie'],
  ['running', 'bieganie'],
  ['cycling', 'kolarstwo', ['jazda na rowerze']],
  ['boxing', 'boks'],
  ['skiing', 'narciarstwo'],
  ['ball', 'pilka'],
  ['goal', 'bramka', ['gol', 'cel']],
  ['team', 'druzyna'],
  ['player', 'zawodnik', ['gracz']],
  ['coach', 'trener'],
  ['match', 'mecz'],
  ['game', 'gra'],
  ['race', 'wyscig', ['rasa']],
  ['stadium', 'stadion'],
  ['medal', 'medal'],
  ['champion', 'mistrz'],
  ['gym', 'silownia'],

  // --- Technika ---
  ['computer', 'komputer'],
  ['phone', 'telefon'],
  ['internet', 'internet'],
  ['screen', 'ekran'],
  ['keyboard', 'klawiatura'],
  ['password', 'haslo'],
  ['email', 'email', ['e-mail']],
  ['camera', 'aparat', ['kamera']],
  ['video', 'wideo', ['film']],
  ['photo', 'zdjecie'],
  ['battery', 'bateria'],
  ['charger', 'ladowarka'],
  ['printer', 'drukarka'],
  ['software', 'oprogramowanie'],
  ['application', 'aplikacja', ['app']],
  ['download', 'pobieranie'],
  ['upload', 'wysylanie'],
  ['file', 'plik'],
  ['folder', 'folder'],
  ['network', 'siec'],
  ['robot', 'robot'],
  ['television', 'telewizor', ['tv']],
  ['radio', 'radio'],

  // --- Transport ---
  ['car', 'samochod', ['auto']],
  ['bus', 'autobus'],
  ['train', 'pociag'],
  ['plane', 'samolot', ['airplane']],
  ['bike', 'rower', ['bicycle']],
  ['boat', 'lodka'],
  ['ship', 'statek'],
  ['taxi', 'taksowka'],
  ['truck', 'ciezarowka'],
  ['motorcycle', 'motocykl'],
  ['road', 'droga'],
  ['street', 'ulica'],
  ['bridge', 'most'],
  ['airport', 'lotnisko'],
  ['station', 'stacja', ['dworzec']],
  ['ticket', 'bilet'],
  ['passenger', 'pasazer'],
  ['wheel', 'kolo'],
  ['engine', 'silnik'],
  ['fuel', 'paliwo'],
  ['map', 'mapa'],
  ['trip', 'podroz', ['wycieczka']],

  // --- Przymiotniki ---
  ['big', 'duzy', ['wielki']],
  ['small', 'maly'],
  ['tall', 'wysoki'],
  ['short', 'krotki', ['niski']],
  ['long', 'dlugi'],
  ['wide', 'szeroki'],
  ['narrow', 'waski'],
  ['fast', 'szybki'],
  ['slow', 'wolny'],
  ['hot', 'goracy'],
  ['cold', 'zimny'],
  ['warm', 'cieply'],
  ['cool', 'chlodny', ['fajny']],
  ['new', 'nowy'],
  ['old', 'stary'],
  ['young', 'mlody'],
  ['good', 'dobry'],
  ['bad', 'zly'],
  ['happy', 'szczesliwy', ['wesoly']],
  ['sad', 'smutny'],
  ['angry', 'zly', ['wsciekly']],
  ['beautiful', 'piekny'],
  ['ugly', 'brzydki'],
  ['easy', 'latwy'],
  ['hard', 'trudny', ['ciezki']],
  ['strong', 'silny'],
  ['weak', 'slaby'],
  ['rich', 'bogaty'],
  ['poor', 'biedny'],
  ['clean', 'czysty'],
  ['dirty', 'brudny'],
  ['full', 'pelny'],
  ['empty', 'pusty'],
  ['open', 'otwarty'],
  ['closed', 'zamkniety'],
  ['quiet', 'cichy'],
  ['loud', 'glosny'],
  ['wet', 'mokry'],
  ['dry', 'suchy'],
  ['dark', 'ciemny'],
  ['bright', 'jasny'],
  ['thin', 'cienki', ['chudy']],
  ['thick', 'gruby'],
  ['near', 'bliski', ['blisko']],
  ['far', 'daleki', ['daleko']],
  ['early', 'wczesny'],
  ['late', 'pozny'],
  ['expensive', 'drogi'],
  ['cheap', 'tani'],
  ['important', 'wazny'],
  ['dangerous', 'niebezpieczny'],
  ['safe', 'bezpieczny'],
  ['funny', 'zabawny'],
  ['boring', 'nudny'],
  ['interesting', 'interesujacy', ['ciekawy']],
  ['famous', 'slynny', ['znany']],
  ['popular', 'popularny'],
  ['different', 'inny', ['rozny']],
  ['brave', 'odwazny'],
  ['kind', 'mily', ['uprzejmy']],
  ['polite', 'uprzejmy'],
  ['rude', 'niegrzeczny'],
  ['honest', 'uczciwy'],
  ['lazy', 'leniwy'],
  ['hungry', 'glodny'],
  ['thirsty', 'spragniony'],
  ['tired', 'zmeczony'],
  ['sick', 'chory', ['ill']],
  ['healthy', 'zdrowy'],
  ['sleepy', 'senny'],
  ['round', 'okragly'],
  ['square', 'kwadratowy'],
  ['flat', 'plaski'],
  ['sharp', 'ostry'],
  ['soft', 'miekki'],
  ['smooth', 'gladki'],
  ['rough', 'szorstki'],
  ['straight', 'prosty'],
  ['curly', 'kedzierzawy', ['krecony']],
  ['tight', 'ciasny'],
  ['loose', 'luzny'],
  ['deep', 'gleboki'],
  ['shallow', 'plytki'],
  ['wild', 'dziki'],
  ['tame', 'oswojony'],
  ['alive', 'zywy'],
  ['dead', 'martwy'],
  ['real', 'prawdziwy'],
  ['fake', 'falszywy'],
  ['correct', 'poprawny'],
  ['true', 'prawdziwy'],
  ['false', 'falszywy'],
  ['possible', 'mozliwy'],
  ['impossible', 'niemozliwy'],
  ['necessary', 'konieczny', ['potrzebny']],
  ['useful', 'przydatny'],
  ['useless', 'bezuzyteczny'],
  ['modern', 'nowoczesny'],
  ['ancient', 'starozytny'],
  ['local', 'lokalny'],
  ['global', 'globalny'],
  ['public', 'publiczny'],
  ['private', 'prywatny'],
  ['national', 'narodowy'],
  ['natural', 'naturalny'],
  ['artificial', 'sztuczny'],
  ['normal', 'normalny'],
  ['strange', 'dziwny', ['weird']],
  ['simple', 'prosty'],
  ['complicated', 'skomplikowany'],
  ['serious', 'powazny'],
  ['silly', 'glupi'],
  ['smart', 'madry', ['sprytny']],
  ['stupid', 'glupi'],
  ['free', 'wolny', ['darmowy']],

  // --- Inne rzeczowniki ---
  ['time', 'czas'],
  ['place', 'miejsce'],
  ['thing', 'rzecz'],
  ['person', 'osoba'],
  ['people', 'ludzie'],
  ['world', 'swiat'],
  ['country', 'kraj'],
  ['city', 'miasto'],
  ['village', 'wies'],
  ['name', 'imie', ['nazwa']],
  ['age', 'wiek'],
  ['life', 'zycie'],
  ['death', 'smierc'],
  ['news', 'wiadomosci'],
  ['problem', 'problem'],
  ['idea', 'pomysl'],
  ['reason', 'powod'],
  ['chance', 'szansa', ['okazja']],
  ['luck', 'szczescie'],
  ['dream', 'marzenie', ['sen']],
  ['secret', 'sekret', ['tajemnica']],
  ['gift', 'prezent', ['present']],
  ['party', 'impreza', ['partia']],
  ['holiday', 'wakacje', ['urlop']],
  ['adventure', 'przygoda'],
  ['story', 'historia', ['opowiadanie']],
  ['newspaper', 'gazeta'],
  ['magazine', 'czasopismo'],
  ['movie', 'film'],
  ['music', 'muzyka'],
  ['song', 'piosenka'],
  ['art', 'sztuka'],
  ['color', 'kolor', ['colour']],
  ['shape', 'ksztalt'],
  ['size', 'rozmiar'],
  ['weight', 'waga'],
  ['price', 'cena'],
  ['sale', 'wyprzedaz'],
  ['shop', 'sklep', ['store']],
  ['market', 'rynek', ['targ']],
  ['church', 'kosciol'],
  ['hospital', 'szpital'],
  ['hotel', 'hotel'],
  ['museum', 'muzeum'],
  ['theatre', 'teatr', ['theater']],
  ['cinema', 'kino'],
  ['park', 'park'],
  ['zoo', 'zoo'],
  ['farm', 'farma', ['gospodarstwo']],
  ['prison', 'wiezienie'],
  ['bakery', 'piekarnia'],
  ['pharmacy', 'apteka'],
  ['supermarket', 'supermarket'],
  ['playground', 'plac zabaw'],
  ['joy', 'radosc'],
  ['fear', 'strach', ['lek']],
  ['anger', 'zlosc'],
  ['surprise', 'zaskoczenie'],
  ['hope', 'nadzieja'],
  ['pride', 'duma'],
  ['shame', 'wstyd'],
  ['jealousy', 'zazdrosc'],
  ['courage', 'odwaga'],
  ['worry', 'zmartwienie'],
  ['corner', 'rog', ['kat']],
  ['edge', 'krawedz'],
  ['center', 'srodek'],
  ['top', 'gora', ['szczyt']],
  ['bottom', 'dol'],
  ['side', 'strona', ['bok']],
  ['front', 'przod'],
  ['direction', 'kierunek'],
  ['distance', 'odleglosc'],
  ['speed', 'predkosc'],
  ['height', 'wysokosc'],
  ['length', 'dlugosc'],
  ['width', 'szerokosc'],
  ['depth', 'glebokosc'],
  ['temperature', 'temperatura'],
  ['pressure', 'cisnienie'],
  ['volume', 'objetosc', ['glosnosc']],
  ['pattern', 'wzor'],
  ['line', 'linia', ['kolejka']],
  ['circle', 'kolo', ['okrag']],
  ['triangle', 'trojkat'],
  ['rectangle', 'prostokat'],

  // --- Podstawy ---
  ['yes', 'tak'],
  ['no', 'nie'],
  ['please', 'prosze'],
  ['thank you', 'dziekuje'],
  ['sorry', 'przepraszam'],
  ['hello', 'czesc', ['hej']],
  ['goodbye', 'do widzenia', ['zegnaj']],

  // --- Uzupelnienie: zwierzeta ---
  ['bull', 'byk'],
  ['calf', 'cielak', ['cielatko']],
  ['lamb', 'jagnie', ['owieczka']],
  ['puppy', 'szczeniak', ['szczenie']],
  ['kitten', 'kotek', ['kociak']],
  ['hippo', 'hipopotam'],
  ['rhino', 'nosorozec'],
  ['gorilla', 'goryl'],
  ['koala', 'koala'],
  ['panda', 'panda'],
  ['cheetah', 'gepard'],
  ['turkey', 'indyk'],

  // --- Uzupelnienie: jedzenie i picie ---
  ['cereal', 'platki sniadaniowe'],
  ['toast', 'grzanka', ['tost']],
  ['pancake', 'nalesnik'],
  ['donut', 'paczek', ['doughnut']],
  ['muffin', 'muffinka'],
  ['pie', 'placek', ['ciasto']],
  ['jelly', 'galaretka'],
  ['mustard', 'musztarda'],
  ['ketchup', 'keczup'],
  ['avocado', 'awokado'],
  ['olive', 'oliwka'],
  ['plum', 'sliwka'],
  ['blueberry', 'jagoda', ['borowka']],
  ['cinnamon', 'cynamon'],

  // --- Uzupelnienie: dom ---
  ['vacuum cleaner', 'odkurzacz'],
  ['hanger', 'wieszak'],
  ['ladder', 'drabina'],
  ['mop', 'mop'],
  ['mailbox', 'skrzynka pocztowa'],
  ['chimney', 'komin'],
  ['balcony', 'balkon'],
  ['attic', 'strych'],
  ['basement', 'piwnica'],
  ['elevator', 'winda', ['lift']],

  // --- Uzupelnienie: ubrania ---
  ['pajamas', 'pizama'],
  ['swimsuit', 'stroj kapielowy', ['kostium kapielowy']],
  ['sandals', 'sandaly'],
  ['boots', 'buty', ['kozaki']],
  ['sneakers', 'trampki', ['adidasy']],
  ['slippers', 'kapcie'],
  ['apron', 'fartuch'],
  ['hoodie', 'bluza z kapturem'],
  ['cap', 'czapka z daszkiem'],
  ['uniform', 'mundur', ['uniform']],

  // --- Uzupelnienie: technika ---
  ['laptop', 'laptop'],
  ['tablet', 'tablet'],
  ['speaker', 'glosnik'],
  ['headphones', 'sluchawki'],
  ['microphone', 'mikrofon'],
  ['button', 'przycisk', ['guzik']],
  ['cable', 'kabel'],
  ['website', 'strona internetowa'],

  // --- Uzupelnienie: sport ---
  ['golf', 'golf'],
  ['hockey', 'hokej'],
  ['rugby', 'rugby'],
  ['baseball', 'baseball'],
  ['helmet', 'kask'],
  ['referee', 'sedzia'],
  ['marathon', 'maraton'],
  ['wrestling', 'zapasy'],
  ['fishing', 'wedkarstwo'],
  ['hiking', 'wedrowanie', ['piesze wycieczki']],

  // --- Uzupelnienie: przyroda ---
  ['waterfall', 'wodospad'],
  ['volcano', 'wulkan'],
  ['cave', 'jaskinia'],
  ['cliff', 'klif', ['urwisko']],
  ['canyon', 'kanion'],
  ['swamp', 'bagno'],
  ['meadow', 'laka'],
  ['jungle', 'dzungla'],
  ['coral', 'koralowiec'],
  ['rainbow', 'tecza'],
  ['thunder', 'grzmot'],
  ['lightning', 'blyskawica', ['piorun']],
  ['hurricane', 'huragan'],
  ['tornado', 'tornado'],

  // --- Uzupelnienie: czas ---
  ['dawn', 'swit'],
  ['dusk', 'zmierzch'],
  ['noon', 'poludnie'],
  ['midnight', 'polnoc'],
  ['decade', 'dekada'],
  ['century', 'wiek', ['stulecie']],
  ['calendar', 'kalendarz'],
  ['anniversary', 'rocznica'],

  // --- Uzupelnienie: zawody i wladza ---
  ['chef', 'szef kuchni'],
  ['scientist', 'naukowiec'],
  ['journalist', 'dziennikarz'],
  ['photographer', 'fotograf'],
  ['electrician', 'elektryk'],
  ['plumber', 'hydraulik'],
  ['mechanic', 'mechanik'],
  ['tailor', 'krawiec'],
  ['barber', 'fryzjer'],
  ['librarian', 'bibliotekarz'],
  ['king', 'krol'],
  ['queen', 'krolowa'],

  // --- Uzupelnienie: zaimki, pytania, spojniki (bez diakrytykow w kluczach PL jak reszta pliku) ---
  ['who', 'kto'],
  ['what', 'co'],
  ['where', 'gdzie'],
  ['when', 'kiedy'],
  ['why', 'dlaczego'],
  ['how', 'jak'],
  ['this', 'to', ['ten', 'ta']],
  ['that', 'tamto', ['tamten', 'tamta']],
  ['here', 'tutaj', ['tu']],
  ['there', 'tam'],
  ['and', 'i', ['oraz']],
  ['or', 'lub', ['albo']],
  ['but', 'ale'],
  ['because', 'poniewaz', ['bo']],
  ['always', 'zawsze'],
  ['never', 'nigdy'],
  ['sometimes', 'czasami', ['czasem']],
  ['together', 'razem'],
  ['alone', 'sam', ['sama']],
  ['everything', 'wszystko'],

  // --- Uzupelnienie: czesci ciala ---
  ['chin', 'broda'],
  ['wrist', 'nadgarstek'],
  ['ankle', 'kostka'],
  ['brain', 'mozg'],
];

/**
 * Zbudowane z RAW: SLOWKA[en] -> podstawowe tlumaczenie, WARIANTY[en] ->
 * dodatkowe akceptowane tlumaczenia (jesli sa). Sprawdzenie duplikatow
 * dzieje sie TUTAJ, raz, przy ladowaniu modulu - lepsze niz cicha nadpisana
 * wartosc w obiekcie, ktora zmniejszylaby liczbe slow bez zadnego ostrzezenia.
 */
export const SLOWKA = {};
export const WARIANTY = {};
{
  const widziane = new Set();
  for (const wpis of RAW) {
    const [en, pl, warianty] = wpis;
    if (widziane.has(en)) {
      throw new Error(`[slowka] Zduplikowane angielskie slowo w RAW: "${en}"`);
    }
    widziane.add(en);
    SLOWKA[en] = pl;
    if (warianty && warianty.length) WARIANTY[en] = warianty;
  }
}

export const ENGLISH_WORDS = Object.keys(SLOWKA);

/**
 * Wszystkie zaakceptowane, ZNORMALIZOWANE (normalizePolish) odpowiedzi dla
 * danego angielskiego slowa: podstawowe tlumaczenie z SLOWKA ORAZ wszystkie
 * wpisy z WARIANTY[word] (jesli sa). Wzorem getWarianty w countries.js.
 */
export function getAkceptowaneWarianty(word) {
  const podstawa = SLOWKA[word] ? [normalizePolish(SLOWKA[word])] : [];
  const dodatkowe = (WARIANTY[word] || []).map(normalizePolish);
  return [...new Set([...podstawa, ...dodatkowe])].filter(Boolean);
}

/** Dzieli juz znormalizowany (normalizePolish) tekst na tablice slow. */
function naSlowa(znormalizowanyTekst) {
  return znormalizowanyTekst.split(/\s+/).filter(Boolean);
}

/** Normalizuje i dzieli na slowa SUROWA odpowiedz z czatu. */
export function tokenizujOdpowiedzSlowka(tekst) {
  return naSlowa(normalizePolish(tekst));
}

/**
 * Indeks WSZYSTKICH akceptowanych wariantow WSZYSTKICH slowek, rozbitych na
 * slowa - {word, slowa}. Budowany raz przy ladowaniu modulu, wzorem
 * INDEKS_WARIANTOW w countries.js. Uzywany w src/tlumaczenia.js do
 * dopasowania odpowiedzi z czatu (dopasowanie CALYMI SLOWAMI, patrz komentarz
 * przy zawieraSekwencje w flagbattle.js - ta sama technika).
 */
export const INDEKS_WARIANTOW_SLOWEK = ENGLISH_WORDS.flatMap((word) =>
  getAkceptowaneWarianty(word).map((wariant) => ({ word, slowa: naSlowa(wariant) })),
).filter((wpis) => wpis.slowa.length > 0);
